### ISSUE TITLE
Webinterface dos not work

### ISSUE THREAD

**Issue by RobinGer** [xkonni/raspberry-remote#20]
Hey,

I really don't know why the webinterface  is not working. When I write the code in the terminal with the code 11111 4 it works. But in the webinterface is does not. My array is ("1" , "11111","04","Nr 1."). 
I actually have no idea what went wrong :(

**Comment by alexh-name** [comment]
I ran into the same problem and found the solution documented in the source of daemon.cpp:
```
 *          16 for plug 1
 *          08 for plug 2
 *          04 for plug 3
 *          02 for plug 4
 *          01 for plug 5
```

So your array should look like this:
`("1" , "11111","02","Nr 1.")`
