### ISSUE TITLE
Webinterface "Could not connect to Socket" Problem Solved

### ISSUE THREAD

**Issue by xraitekx** [xkonni/raspberry-remote#21]
I had a Problem with the new Webinterface.
So i entered my housecode in systemcode and ran into that "Could not connect to socket" problem.

I couldn´t conect to the Socket because i thought that the systemcode is the housecode (f.e 10111), but the housecode is in the config.php the "group".

I have the "Brennenstuhl" Plugs and the Plugcode is in my case:
16 for A
08 for B
04 for C
02 for D
01 for E

So here is the solution for guys who have the same problem:

![raspberry-remote](https://cloud.githubusercontent.com/assets/25708606/22855519/c2bf9cea-f081-11e6-832a-487768faa777.PNG)

**Comment by GFMsoft** [comment]
Had the same problem. The documentation inside is very confusing.

When ./send 11111 02 1 works and youll enter it inside the config.php and it won't work it's darn annoying.
So thank you for the solution here.
