### ISSUE TITLE
webinterface - Intertechno switches don't work

### ISSUE THREAD

**Issue by iVarco** [xkonni/raspberry-remote#22]
As far as I use the array ("2" , "01","01","Intertechno 1") within the config.php file,
the daemon gives me an error output (elro switches are working):

message: 111111042
nSys: 1
nGroup: 11111
nSwitchNumber: 4
nAction: 2
nAddr: 996
nPlugs: 1024

message: 201012
nSys: 2
nGroup: 01
nSwitchNumber: 1
nAction: 2
nAddr: 33
nPlugs: 1024
**Switch out of range: 01:1**

Strange thing is, Intertechno Switches can't even be clicked on, they neither get switched nor the status is updating.

Any Idea?

**Comment by FooDeas** [comment]
Pull request incoming soon.

**Comment by iVarco** [comment]
Working now. :)
this dude saved my weekend.

cheers!
