### ISSUE TITLE
Checking the status

### ISSUE THREAD

**Issue by henits** [xkonni/raspberry-remote#30]
I already had a script which had the output 0 or 1 depending on the state of the socket, but I can not find it anymore. Does anybody else have a php script for me?

**Comment by tillepille** [comment]
check webinterface/status.php

**Comment by henits** [comment]
But does it return the status of each single socket?

**Comment by tillepille** [comment]
The status.php works pretty similar to the other files. 
You do a GET to yourserver/status/?sys=1&group=1010&switch=01 and the respond is a plain text "0" or "1" depending on the status, of course. 

Thats the same what the index.php does for each socket to show you the right status.
Hope this helps...

**Comment by henits** [comment]
Thank you so much! Really appreciate it!
